import { useEffect, useMemo, useState } from "react";
import {
  Activity,
  AlertTriangle,
  Bot,
  CheckCircle2,
  CircleHelp,
  ClipboardCheck,
  Database,
  FileText,
  Gauge,
  GitBranch,
  LockKeyhole,
  Network,
  RefreshCcw,
  Search,
  ShieldAlert,
  ShieldCheck,
  UploadCloud,
  Users,
  Wrench
} from "lucide-react";
import {
  Background,
  Controls,
  Edge,
  MarkerType,
  MiniMap,
  Node,
  Panel,
  ReactFlow,
  useEdgesState,
  useNodesState
} from "@xyflow/react";
import { api } from "./lib/api";
import type {
  AccessMatrix,
  AuditEvent,
  DeidentificationRow,
  FindingDetail,
  FindingSummary,
  GraphEdgeDto,
  GraphNodeDto,
  GraphPayload,
  RemediationPayload,
  ReportPayload,
  ScanRun,
  Severity,
  SourceInfo,
  Summary
} from "./types";

type Tab = "import" | "dashboard" | "map" | "findings" | "remediation" | "deid" | "access" | "report";

type AppData = {
  source: SourceInfo;
  summary: Summary;
  graph: GraphPayload;
  findings: FindingSummary[];
  deidentification: DeidentificationRow[];
  access: AccessMatrix;
  remediations: RemediationPayload;
  report: ReportPayload;
  scanRuns: ScanRun[];
  auditEvents: AuditEvent[];
};

type UploadOverlayState = {
  phase: "analyzing" | "complete";
  projectName: string;
  fileCount: number;
};

const tabs: Array<{ id: Tab; label: string; icon: typeof Gauge }> = [
  { id: "import", label: "Import", icon: UploadCloud },
  { id: "dashboard", label: "Dashboard", icon: Gauge },
  { id: "map", label: "Data Map", icon: Network },
  { id: "findings", label: "Findings", icon: ShieldAlert },
  { id: "remediation", label: "Remediation", icon: Wrench },
  { id: "deid", label: "De-ID", icon: ClipboardCheck },
  { id: "access", label: "Access", icon: Users },
  { id: "report", label: "Report", icon: FileText }
];

const metricHelp = {
  riskScore:
    "Highest open finding score in this scan. The engine combines impact, likelihood, exposure, control gaps, and classifier confidence, then adds rule-specific severity boosts.",
  critical:
    "Open findings scored 85-100. These usually combine direct identifiers with health/payment context, broad exposure, or unsafe downstream movement.",
  high:
    "Open findings scored 70-84. These are serious patterns that should be reviewed soon, but they have lower exposure, confidence, or control gaps than critical items.",
  phiAssets:
    "Tables, views, or exports containing PHI-risk labels such as direct identifiers, quasi-identifiers, health/payment context, free text, or AI exposure.",
  freeText:
    "Text-like columns with note, message, log, prompt, or comment signals that may hide identifiers inside unstructured content.",
  destinations:
    "External vendors or AI/data destinations modeled in the scan graph that can inherit PHI risk from upstream assets.",
  openFindings:
    "Open potential-risk findings generated by deterministic scanner rules. They are risk indicators, not legal conclusions.",
  deid:
    "Average Safe Harbor readiness score across scanned datasets. Lower scores mean more identifier or free-text blockers remain."
} as const;

const factorHelp: Record<string, string> = {
  impact: "Sensitivity of the data involved, such as SSN, MRN, email, DOB, diagnosis, medication, claim, or free-text patient details.",
  likelihood: "How likely the pattern is to be misused or disclosed based on role breadth, dataset purpose, destination, or free-text/log exposure.",
  exposure: "Estimated blast radius from row count, downstream edges, affected assets, roles, and destinations.",
  control_gap: "How much protective evidence appears missing, such as masking, audit logging, RBAC narrowing, redaction, or export controls.",
  confidence: "How strongly schema names, value patterns, relationships, and access evidence support the finding."
};

const deidCategoryHelp: Record<string, string> = {
  name: "Name-like columns block Safe Harbor-style readiness unless removed or transformed.",
  dob: "Full birth dates and most exact dates are identifiers. Year-only or generalized dates may be needed depending on the use case.",
  geography: "Street addresses, city/state details, and small geographic subdivisions can make people re-identifiable.",
  zip: "ZIP/postal fields may need generalization. Safe Harbor has special ZIP handling rules.",
  phone: "Phone numbers are direct identifiers and should be removed, masked, or tokenized before de-identified export.",
  email: "Email addresses are direct identifiers and should not appear in de-identified datasets.",
  mrn: "Medical record numbers are direct identifiers and high-priority removal targets.",
  ssn: "Social Security numbers are direct identifiers and usually a critical blocker.",
  ip: "IP addresses and similar device/network identifiers can block de-identification readiness.",
  free_text: "Notes, logs, messages, prompts, and comments may hide identifiers even when structured columns look clean."
};

const severityHelp: Record<Severity, string> = {
  critical: "Score 85-100. Fix first or document a reviewed risk decision.",
  high: "Score 70-84. Review quickly and plan remediation.",
  moderate: "Score 40-69. Validate and queue behind critical/high work.",
  low: "Score below 40. Track as lower-priority evidence or hygiene."
};

const uploadSuccessHoldMs = 1450;

async function fetchAppData(): Promise<AppData> {
  const [source, summary, graph, findings, deidentification, access, remediations, report, scanRuns, auditEvents] = await Promise.all([
    api.source(),
    api.summary(),
    api.graph(),
    api.findings(),
    api.deidentification(),
    api.accessMatrix(),
    api.remediations(),
    api.report(),
    api.scanRuns(),
    api.auditEvents()
  ]);
  return { source, summary, graph, findings, deidentification, access, remediations, report, scanRuns, auditEvents };
}

export function App() {
  const [activeTab, setActiveTab] = useState<Tab>("dashboard");
  const [data, setData] = useState<AppData | null>(null);
  const [selectedFindingId, setSelectedFindingId] = useState<string | null>(null);
  const [selectedFinding, setSelectedFinding] = useState<FindingDetail | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [actionError, setActionError] = useState<string | null>(null);
  const [actionBusy, setActionBusy] = useState(false);
  const [uploadOverlay, setUploadOverlay] = useState<UploadOverlayState | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    let cancelled = false;
    async function load() {
      try {
        setLoading(true);
        const nextData = await fetchAppData();
        if (cancelled) return;
        setData(nextData);
        setSelectedFindingId(nextData.findings[0]?.id ?? null);
        setError(null);
      } catch (err) {
        if (cancelled) return;
        setError(err instanceof Error ? err.message : "Unable to load intelligence data");
      } finally {
        if (!cancelled) setLoading(false);
      }
    }
    load();
    return () => {
      cancelled = true;
    };
  }, []);

  async function refreshAfterSourceChange() {
    const nextData = await fetchAppData();
    setData(nextData);
    setSelectedFindingId(nextData.findings[0]?.id ?? null);
    setActiveTab("dashboard");
  }

  async function handleUpload(files: File[], projectName: string) {
    const safeProjectName = projectName.trim() || "Uploaded Data Project";
    try {
      setActionBusy(true);
      setActionError(null);
      setUploadOverlay({ phase: "analyzing", projectName: safeProjectName, fileCount: files.length });
      await api.upload(files, safeProjectName);
      await refreshAfterSourceChange();
      setUploadOverlay({ phase: "complete", projectName: safeProjectName, fileCount: files.length });
      window.setTimeout(() => {
        setUploadOverlay((current) => (current?.phase === "complete" ? null : current));
      }, uploadSuccessHoldMs);
    } catch (err) {
      setActionError(err instanceof Error ? err.message : "Upload scan failed");
      setUploadOverlay(null);
    } finally {
      setActionBusy(false);
    }
  }

  async function handleResetDemo() {
    try {
      setActionBusy(true);
      setActionError(null);
      await api.resetDemo();
      await refreshAfterSourceChange();
    } catch (err) {
      setActionError(err instanceof Error ? err.message : "Could not reset demo scan");
    } finally {
      setActionBusy(false);
    }
  }

  useEffect(() => {
    let cancelled = false;
    if (!selectedFindingId) {
      setSelectedFinding(null);
      return;
    }
    api
      .finding(selectedFindingId)
      .then((finding) => {
        if (!cancelled) setSelectedFinding(finding);
      })
      .catch(() => {
        if (!cancelled) setSelectedFinding(null);
      });
    return () => {
      cancelled = true;
    };
  }, [selectedFindingId]);

  if (loading) {
    return (
      <Shell activeTab={activeTab} onTab={setActiveTab}>
        <div className="loading">
          <RefreshCcw className="spin" size={22} />
          <span>Loading scan</span>
        </div>
      </Shell>
    );
  }

  if (error || !data) {
    return (
      <Shell activeTab={activeTab} onTab={setActiveTab}>
        <section className="empty-state">
          <AlertTriangle size={24} />
          <h2>API unavailable</h2>
          <p>{error}</p>
          <code>$env:PYTHONPATH="apps/scanner"; python -m uvicorn apps.api.app.main:app --reload --port 8000</code>
        </section>
      </Shell>
    );
  }

  return (
    <Shell
      activeTab={activeTab}
      onTab={setActiveTab}
      blocked={uploadOverlay !== null}
      overlay={uploadOverlay ? <UploadAnalysisOverlay state={uploadOverlay} /> : null}
    >
      {activeTab === "import" && (
        <ImportPanel
          source={data.source}
          scanRuns={data.scanRuns}
          auditEvents={data.auditEvents}
          busy={actionBusy}
          error={actionError}
          onUpload={handleUpload}
          onResetDemo={handleResetDemo}
        />
      )}
      {activeTab === "dashboard" && (
        <Dashboard
          summary={data.summary}
          findings={data.findings}
          onOpenFinding={(id) => {
            setSelectedFindingId(id);
            setActiveTab("findings");
          }}
        />
      )}
      {activeTab === "map" && (
        <DataMap
          graph={data.graph}
          findings={data.findings}
          onOpenFinding={(id) => {
            setSelectedFindingId(id);
            setActiveTab("findings");
          }}
        />
      )}
      {activeTab === "findings" && (
        <FindingsPanel
          findings={data.findings}
          selectedFinding={selectedFinding}
          selectedFindingId={selectedFindingId}
          onSelect={setSelectedFindingId}
        />
      )}
      {activeTab === "remediation" && (
        <RemediationPanel
          payload={data.remediations}
          onOpenFinding={(id) => {
            setSelectedFindingId(id);
            setActiveTab("findings");
          }}
        />
      )}
      {activeTab === "deid" && <DeidentificationPanel rows={data.deidentification} />}
      {activeTab === "access" && <AccessPanel matrix={data.access} />}
      {activeTab === "report" && <ReportPanel report={data.report} />}
    </Shell>
  );
}

function Shell({
  activeTab,
  onTab,
  children,
  blocked = false,
  overlay
}: {
  activeTab: Tab;
  onTab: (tab: Tab) => void;
  children: React.ReactNode;
  blocked?: boolean;
  overlay?: React.ReactNode;
}) {
  return (
    <>
      <div className={`app-shell${blocked ? " is-muted" : ""}`} aria-hidden={blocked}>
        <aside className="sidebar">
          <div className="brand">
            <div className="brand-mark">
              <ShieldCheck size={22} />
            </div>
            <div>
              <strong>PHI Guard</strong>
              <span>Intelligence</span>
            </div>
          </div>
          <nav>
            {tabs.map((tab) => {
              const Icon = tab.icon;
              return (
                <button
                  key={tab.id}
                  className={activeTab === tab.id ? "active" : ""}
                  onClick={() => onTab(tab.id)}
                  title={tab.label}
                  disabled={blocked}
                >
                  <Icon size={18} />
                  <span>{tab.label}</span>
                </button>
              );
            })}
          </nav>
          <div className="scan-badge">
            <Activity size={16} />
            <span>Demo scan</span>
          </div>
        </aside>
        <main className="main">{children}</main>
      </div>
      {overlay}
    </>
  );
}

function UploadAnalysisOverlay({ state }: { state: UploadOverlayState }) {
  const complete = state.phase === "complete";
  return (
    <div className="analysis-overlay" role="dialog" aria-modal="true" aria-live="polite">
      <section className={`analysis-modal${complete ? " complete" : ""}`}>
        <div className="success-orbits" aria-hidden="true">
          <span />
          <span />
          <span />
        </div>
        <div className="analysis-icon">
          {complete ? <CheckCircle2 size={38} /> : <RefreshCcw className="spin" size={34} />}
        </div>
        <p className="eyebrow">{complete ? "Analysis updated" : "Analyzing upload"}</p>
        <h2>{complete ? "Risk intelligence map is ready" : "Scanning file structures and PHI patterns"}</h2>
        <p>
          {complete
            ? `${state.projectName} has been analyzed. Redirecting to the dashboard.`
            : `${state.fileCount} file${state.fileCount === 1 ? "" : "s"} locked for analysis. The workspace will update when the scan is complete.`}
        </p>
        <div className="analysis-steps" aria-hidden="true">
          <span className={complete ? "done" : "active"}>Parse</span>
          <span className={complete ? "done" : "active delay-1"}>Classify</span>
          <span className={complete ? "done" : "active delay-2"}>Score</span>
          <span className={complete ? "done" : "active delay-3"}>Visualize</span>
        </div>
      </section>
    </div>
  );
}

function Dashboard({
  summary,
  findings,
  onOpenFinding
}: {
  summary: Summary;
  findings: FindingSummary[];
  onOpenFinding: (id: string) => void;
}) {
  return (
    <div className="page-grid">
      <header className="page-header">
        <div>
          <p className="eyebrow">Workspace</p>
          <h1>{summary.workspace}</h1>
        </div>
        <div className="scan-meta">
          <span>{summary.scan_id}</span>
          <strong>{formatDate(summary.generated_at)}</strong>
        </div>
      </header>

      <section className="metric-grid">
        <Metric icon={Gauge} label="Risk score" value={summary.risk_score} tone="critical" tooltip={metricHelp.riskScore} />
        <Metric icon={ShieldAlert} label="Critical" value={summary.critical_findings} tone="critical" tooltip={metricHelp.critical} />
        <Metric icon={AlertTriangle} label="High" value={summary.high_findings} tone="high" tooltip={metricHelp.high} />
        <Metric icon={Database} label="PHI assets" value={summary.phi_assets} tone="moderate" tooltip={metricHelp.phiAssets} />
        <Metric icon={GitBranch} label="Free text" value={summary.free_text_fields} tone="high" tooltip={metricHelp.freeText} />
        <Metric icon={Bot} label="Destinations" value={summary.external_destinations} tone="moderate" tooltip={metricHelp.destinations} />
      </section>

      <section className="two-column">
        <div className="panel">
          <div className="panel-header">
            <h2>Top Findings</h2>
            <span className="pill">{summary.open_findings} open <InfoTooltip text={metricHelp.openFindings} /></span>
          </div>
          <div className="finding-list compact">
            {findings.slice(0, 7).map((finding) => (
              <button key={finding.id} onClick={() => onOpenFinding(finding.id)}>
                <SeverityBadge severity={finding.severity} />
                <span>{finding.title}</span>
                <strong>{finding.risk_score}</strong>
              </button>
            ))}
          </div>
        </div>
        <div className="panel">
          <div className="panel-header">
            <h2>Risk Trend</h2>
            <span className="pill readiness">{summary.deidentification_readiness_score}% De-ID <InfoTooltip text={metricHelp.deid} /></span>
          </div>
          <div className="trend-chart" aria-label="Risk trend chart">
            {summary.trend.map((point) => (
              <div key={point.period} className="trend-column">
                <div className="trend-bars">
                  <span className="bar critical" style={{ height: `${point.critical * 16}px` }} />
                  <span className="bar high" style={{ height: `${point.high * 8}px` }} />
                  <span className="bar resolved" style={{ height: `${point.resolved * 8}px` }} />
                </div>
                <small>{point.period}</small>
              </div>
            ))}
          </div>
        </div>
      </section>
    </div>
  );
}

function Metric({
  icon: Icon,
  label,
  value,
  tone,
  tooltip
}: {
  icon: typeof Gauge;
  label: string;
  value: number;
  tone: "critical" | "high" | "moderate";
  tooltip?: string;
}) {
  return (
    <div className={`metric ${tone}`}>
      <div>
        <Icon size={18} />
        <span>{label}</span>
        {tooltip && <InfoTooltip text={tooltip} />}
      </div>
      <strong>{value}</strong>
    </div>
  );
}

function InfoTooltip({ text }: { text: string }) {
  return (
    <span className="tooltip" tabIndex={0} aria-label={text}>
      <CircleHelp size={14} aria-hidden="true" />
      <span className="tooltip-panel" role="tooltip">{text}</span>
    </span>
  );
}

function HoverExplain({ text, children }: { text: string; children: React.ReactNode }) {
  return (
    <span className="hover-explain" tabIndex={0} aria-label={text}>
      {children}
      <span className="tooltip-panel" role="tooltip">{text}</span>
    </span>
  );
}

function ImportPanel({
  source,
  scanRuns,
  auditEvents,
  busy,
  error,
  onUpload,
  onResetDemo
}: {
  source: SourceInfo;
  scanRuns: ScanRun[];
  auditEvents: AuditEvent[];
  busy: boolean;
  error: string | null;
  onUpload: (files: File[], projectName: string) => Promise<void>;
  onResetDemo: () => Promise<void>;
}) {
  const [files, setFiles] = useState<File[]>([]);
  const [projectName, setProjectName] = useState(source.mode === "upload" ? source.workspace : "Uploaded Data Project");

  function handleFileChange(event: React.ChangeEvent<HTMLInputElement>) {
    setFiles(Array.from(event.target.files ?? []));
  }

  async function handleSubmit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault();
    if (!files.length) return;
    await onUpload(files, projectName.trim() || "Uploaded Data Project");
  }

  return (
    <div className="page-grid">
      <header className="page-header">
        <div>
          <p className="eyebrow">Source</p>
          <h1>Import Data</h1>
        </div>
        <div className="scan-meta">
          <span>{source.mode}</span>
          <strong>{source.scan_id}</strong>
        </div>
      </header>
      <section className="import-layout">
        <form className="panel import-panel" onSubmit={handleSubmit}>
          <label>
            <span>Project name</span>
            <input value={projectName} onChange={(event) => setProjectName(event.target.value)} />
          </label>
          <label className="file-drop">
            <UploadCloud size={26} />
            <strong>{files.length ? `${files.length} file${files.length === 1 ? "" : "s"} selected` : "Choose project files"}</strong>
            <span>CSV, TSV, JSON, JSONL, XML, SQLite, SQL, logs, text, or ZIP</span>
            <input
              type="file"
              multiple
              accept=".csv,.tsv,.json,.jsonl,.ndjson,.xml,.sqlite,.sqlite3,.db,.sql,.log,.txt,.zip"
              onChange={handleFileChange}
            />
          </label>
          {files.length > 0 && (
            <div className="selected-files">
              {files.map((file) => (
                <span key={`${file.name}-${file.size}`}>{file.name}</span>
              ))}
            </div>
          )}
          {error && <p className="inline-error">{error}</p>}
          <div className="button-row">
            <button className="primary-action" type="submit" disabled={busy || !files.length}>
              <UploadCloud size={16} />
              <span>{busy ? "Analyzing" : "Analyze Upload"}</span>
            </button>
            <button className="secondary-action" type="button" disabled={busy} onClick={onResetDemo}>
              <RefreshCcw size={16} />
              <span>Reset Demo</span>
            </button>
          </div>
        </form>
        <div className="panel source-panel">
          <div className="panel-header">
            <h2>Active Scan</h2>
            <span className="pill">{source.mode}</span>
          </div>
          <dl className="source-list">
            <div>
              <dt>Workspace</dt>
              <dd>{source.workspace}</dd>
            </div>
            <div>
              <dt>Generated</dt>
              <dd>{formatDate(source.generated_at)}</dd>
            </div>
            <div>
              <dt>Parsed files</dt>
              <dd>{source.parsed_files.length}</dd>
            </div>
            <div>
              <dt>Unsupported</dt>
              <dd>{source.unsupported_files.length}</dd>
            </div>
          </dl>
          {(source.parsed_files.length > 0 || source.unsupported_files.length > 0 || source.warnings.length > 0) && (
            <div className="source-events">
              {source.parsed_files.map((file) => (
                <span key={`parsed-${file}`} className="ok">{file}</span>
              ))}
              {source.unsupported_files.map((file) => (
                <span key={`unsupported-${file}`} className="warn">{file}</span>
              ))}
              {source.warnings.map((warning) => (
                <span key={`warning-${warning}`} className="warn">{warning}</span>
              ))}
            </div>
          )}
        </div>
      </section>
      <section className="two-column">
        <div className="panel">
          <div className="panel-header">
            <h2>Scan History</h2>
            <span className="pill">{scanRuns.length} stored</span>
          </div>
          <div className="history-list">
            {scanRuns.slice(0, 6).map((run, index) => {
              const summary = run.summary ?? run.summary_json ?? {};
              return (
                <article key={`${run.scan_id ?? run.created_at}-${index}`}>
                  <strong>{run.workspace ?? "Workspace"}</strong>
                  <span>{run.source ?? "scan"} - {run.status ?? "completed"}</span>
                  <small>{summary.finding_count ?? 0} findings - {summary.critical_count ?? 0} critical</small>
                </article>
              );
            })}
          </div>
        </div>
        <div className="panel">
          <div className="panel-header">
            <h2>Audit Events</h2>
            <span className="pill">latest</span>
          </div>
          <div className="history-list">
            {auditEvents.slice(0, 6).map((event, index) => (
              <article key={`${event.created_at}-${event.event_type}-${index}`}>
                <strong>{event.event_type.replaceAll("_", " ")}</strong>
                <span>{event.actor ?? event.actor_id ?? "system"} - {event.workspace ?? "workspace"}</span>
                <small>{formatDate(event.created_at)}</small>
              </article>
            ))}
          </div>
        </div>
      </section>
    </div>
  );
}

function DataMap({
  graph,
  findings,
  onOpenFinding
}: {
  graph: GraphPayload;
  findings: FindingSummary[];
  onOpenFinding: (id: string) => void;
}) {
  const [query, setQuery] = useState("");
  const [showRoles, setShowRoles] = useState(true);
  const [showFindings, setShowFindings] = useState(true);
  const visibleNodeDtos = useMemo(() => {
    const normalizedQuery = query.trim().toLowerCase();
    return graph.nodes.filter((node) => {
      if (!showRoles && node.type === "role") return false;
      if (!showFindings && node.type === "finding") return false;
      if (!normalizedQuery) return true;
      return (
        node.label.toLowerCase().includes(normalizedQuery) ||
        node.type.toLowerCase().includes(normalizedQuery) ||
        node.classifications.some((label) => label.toLowerCase().includes(normalizedQuery))
      );
    });
  }, [graph.nodes, query, showFindings, showRoles]);
  const visibleIds = useMemo(() => new Set(visibleNodeDtos.map((node) => node.id)), [visibleNodeDtos]);
  const findingById = useMemo(() => new Map(findings.map((finding) => [finding.id, finding])), [findings]);
  const initialNodes = useMemo(() => layoutNodes(visibleNodeDtos, findingById), [visibleNodeDtos, findingById]);
  const initialEdges = useMemo(
    () => layoutEdges(graph.edges.filter((edge) => visibleIds.has(edge.source) && visibleIds.has(edge.target))),
    [graph.edges, visibleIds]
  );
  const [nodes, setNodes, onNodesChange] = useNodesState(initialNodes);
  const [edges, setEdges, onEdgesChange] = useEdgesState(initialEdges);

  useEffect(() => {
    setNodes(initialNodes);
    setEdges(initialEdges);
  }, [initialNodes, initialEdges, setEdges, setNodes]);

  return (
    <div className="map-page">
      <header className="page-header">
        <div>
          <p className="eyebrow">Intelligence graph</p>
          <h1>Data Risk Map</h1>
        </div>
        <div className="toolbar">
          <label className="search-box">
            <Search size={17} />
            <input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search assets" />
          </label>
          <button className={showRoles ? "toggle active" : "toggle"} onClick={() => setShowRoles((value) => !value)}>
            <Users size={16} />
            <span>Roles</span>
          </button>
          <button className={showFindings ? "toggle active" : "toggle"} onClick={() => setShowFindings((value) => !value)}>
            <ShieldAlert size={16} />
            <span>Findings</span>
          </button>
        </div>
      </header>
      <section className="graph-surface">
        <ReactFlow nodes={nodes} edges={edges} onNodesChange={onNodesChange} onEdgesChange={onEdgesChange} fitView>
          <Background color="#d8dee4" gap={18} />
          <MiniMap pannable zoomable nodeStrokeWidth={3} />
          <Controls />
          <Panel position="top-right" className="graph-legend">
            <span><i className="legend critical" /> Critical</span>
            <span><i className="legend high" /> High</span>
            <span><i className="legend moderate" /> Moderate</span>
            <span><i className="legend low" /> Low</span>
          </Panel>
        </ReactFlow>
      </section>
      <section className="horizontal-list">
        {findings.slice(0, 6).map((finding) => (
          <button key={finding.id} onClick={() => onOpenFinding(finding.id)}>
            <SeverityBadge severity={finding.severity} />
            <span>{finding.title}</span>
          </button>
        ))}
      </section>
    </div>
  );
}

function FindingsPanel({
  findings,
  selectedFinding,
  selectedFindingId,
  onSelect
}: {
  findings: FindingSummary[];
  selectedFinding: FindingDetail | null;
  selectedFindingId: string | null;
  onSelect: (id: string) => void;
}) {
  return (
    <div className="findings-page">
      <header className="page-header">
        <div>
          <p className="eyebrow">Risk reasoning</p>
          <h1>Finding Detail</h1>
        </div>
      </header>
      <section className="finding-layout">
        <aside className="finding-list">
          {findings.map((finding) => (
            <button
              key={finding.id}
              className={selectedFindingId === finding.id ? "selected" : ""}
              onClick={() => onSelect(finding.id)}
            >
              <SeverityBadge severity={finding.severity} />
              <span>{finding.title}</span>
              <strong>{finding.risk_score}</strong>
            </button>
          ))}
        </aside>
        <article className="detail-panel">
          {selectedFinding ? (
            <>
              <div className="detail-title">
                <SeverityBadge severity={selectedFinding.severity} />
                <h2>{selectedFinding.title}</h2>
                <HoverExplain text={`Risk score ${selectedFinding.risk_score}. ${metricHelp.riskScore}`}>
                  <span className="score">{selectedFinding.risk_score}</span>
                </HoverExplain>
              </div>
              <div className="detail-grid">
                <DetailBlock title="Observation" text={selectedFinding.observation} />
                <DetailBlock title="Why It Matters" text={selectedFinding.why_it_matters} />
                <DetailBlock title="Remediation" text={selectedFinding.remediation_summary} />
                <DetailBlock title="Human Review" text={selectedFinding.human_review} />
              </div>
              <div className="factor-grid">
                {Object.entries(selectedFinding.risk_factors).map(([key, value]) => (
                  <div key={key} className="factor">
                    <span>{labelize(key)} <InfoTooltip text={factorHelp[key] ?? "Risk factor used in the explainable score."} /></span>
                    <div className="factor-track">
                      <i style={{ width: `${Math.round(value * 100)}%` }} />
                    </div>
                    <strong>{Math.round(value * 100)}%</strong>
                  </div>
                ))}
              </div>
              <div className="split-block">
                <section>
                  <h3>Evidence</h3>
                  {selectedFinding.evidence.map((item) => (
                    <div key={`${item.evidence_type}-${item.safe_snippet}`} className="evidence-row">
                      <LockKeyhole size={15} />
                      <span>{item.safe_snippet}</span>
                      <code>raw_value_stored={String(item.raw_value_stored)}</code>
                    </div>
                  ))}
                </section>
                <section>
                  <h3>Recommended Steps</h3>
                  <ol className="steps">
                    {selectedFinding.recommended_steps.map((step) => (
                      <li key={step}>{step}</li>
                    ))}
                  </ol>
                </section>
              </div>
            </>
          ) : (
            <div className="empty-state">
              <AlertTriangle size={22} />
              <h2>No finding selected</h2>
            </div>
          )}
        </article>
      </section>
    </div>
  );
}

function DetailBlock({ title, text }: { title: string; text: string }) {
  return (
    <section className="detail-block">
      <h3>{title}</h3>
      <p>{text}</p>
    </section>
  );
}

function RemediationPanel({
  payload,
  onOpenFinding
}: {
  payload: RemediationPayload;
  onOpenFinding: (id: string) => void;
}) {
  const ownerEntries = Object.entries(payload.summary.by_owner);
  return (
    <div className="page-grid">
      <header className="page-header">
        <div>
          <p className="eyebrow">Fix-first queue</p>
          <h1>Remediation Backlog</h1>
        </div>
        <div className="scan-meta">
          <span>Projected reduction</span>
          <strong>
            {payload.summary.estimated_risk_reduction} pts{" "}
            <InfoTooltip text="Estimated point reduction if the current top priority tasks are completed. This is a planning signal, not a guarantee." />
          </strong>
        </div>
      </header>
      <section className="metric-grid remediation-metrics">
        <Metric icon={Wrench} label="Open tasks" value={payload.summary.total} tone="moderate" tooltip="Generated remediation tasks derived from open findings." />
        <Metric icon={ShieldAlert} label="Critical-linked" value={payload.summary.critical} tone="critical" tooltip="Tasks tied to critical findings. These should usually be handled first." />
        <Metric icon={AlertTriangle} label="High-linked" value={payload.summary.high} tone="high" tooltip="Tasks tied to high-severity findings." />
      </section>
      <section className="two-column">
        <div className="panel">
          <div className="panel-header">
            <h2>Priority Queue</h2>
            <span className="pill">{payload.items.slice(0, 8).length} next</span>
          </div>
          <div className="task-list">
            {payload.items.slice(0, 8).map((task) => (
              <button key={task.id} onClick={() => onOpenFinding(task.finding_id)}>
                <div className="task-main">
                  <SeverityBadge severity={task.severity} />
                  <strong>{task.title}</strong>
                  <span>{task.owner} - {task.due_window} - effort {task.effort}</span>
                </div>
                <div className="task-score">
                  <strong>{task.risk_score}</strong>
                  <span>-{task.risk_reduction}</span>
                </div>
              </button>
            ))}
          </div>
        </div>
        <div className="panel">
          <div className="panel-header">
            <h2>Owner Load</h2>
            <span className="pill">open</span>
          </div>
          <div className="owner-load">
            {ownerEntries.map(([owner, count]) => (
              <div key={owner}>
                <span>{owner}</span>
                <strong>{count}</strong>
                <i style={{ width: `${Math.max(12, count * 12)}%` }} />
              </div>
            ))}
          </div>
        </div>
      </section>
      <section className="table-panel">
        <table className="remediation-table">
          <thead>
            <tr>
              <th>Task</th>
              <th>Owner</th>
              <th>Controls</th>
              <th>Due</th>
              <th>Effort</th>
              <th>Risk</th>
            </tr>
          </thead>
          <tbody>
            {payload.items.map((task) => (
              <tr key={task.id}>
                <td>
                  <button className="link-button" onClick={() => onOpenFinding(task.finding_id)}>
                    {task.title}
                  </button>
                  <span>{task.human_review}</span>
                </td>
                <td><strong>{task.owner}</strong></td>
                <td>{task.control_mapping.join(", ")}</td>
                <td>{task.due_window}</td>
                <td>{task.effort}</td>
                <td><strong>{task.risk_score}</strong></td>
              </tr>
            ))}
          </tbody>
        </table>
      </section>
    </div>
  );
}

function DeidentificationPanel({ rows }: { rows: DeidentificationRow[] }) {
  const categories = ["name", "dob", "geography", "zip", "phone", "email", "mrn", "ssn", "ip", "free_text"];
  return (
    <div className="page-grid">
      <header className="page-header">
        <div>
          <p className="eyebrow">Safe Harbor readiness</p>
          <h1>De-identification Heatmap</h1>
        </div>
      </header>
      <section className="table-panel">
        <table className="heatmap">
          <thead>
            <tr>
              <th>Dataset</th>
              {categories.map((category) => (
                <th key={category}>
                  <span className="th-label">{labelize(category)} <InfoTooltip text={deidCategoryHelp[category]} /></span>
                </th>
              ))}
              <th><span className="th-label">Status <InfoTooltip text="Not ready means three or more blocker categories were detected. Review means at least one blocker remains. Likely ready still requires human review." /></span></th>
              <th><span className="th-label">Score <InfoTooltip text="Starts at 100 and subtracts for detected identifier/free-text blocker categories. It supports review; it does not certify de-identification." /></span></th>
            </tr>
          </thead>
          <tbody>
            {rows.map((row) => (
              <tr key={row.table}>
                <td>
                  <strong>{row.table}</strong>
                  <span>{row.row_count_estimate.toLocaleString()} rows</span>
                </td>
                {categories.map((category) => {
                  const blockers = row.blockers[category] ?? [];
                  const explanation = blockers.length
                    ? `${labelize(category)} blocker detected in ${blockers.join(", ")}. ${deidCategoryHelp[category]}`
                    : `No ${labelize(category).toLowerCase()} blocker detected from schema and masked value profiling.`;
                  return (
                    <td key={category} className={blockers.length ? "blocked" : "clear"}>
                      <HoverExplain text={explanation}>{blockers.length ? blockers.length : "0"}</HoverExplain>
                    </td>
                  );
                })}
                <td>
                  <HoverExplain text={`${row.status}: ${row.table} has ${Object.values(row.blockers).filter((items) => items.length).length} blocker categories detected.`}>
                    <span className={`status ${statusClass(row.status)}`}>{row.status}</span>
                  </HoverExplain>
                </td>
                <td>
                  <HoverExplain text={`Readiness score ${row.readiness_score}. Lower scores mean more Safe Harbor identifier or free-text blocker categories were detected.`}>
                    <strong>{row.readiness_score}</strong>
                  </HoverExplain>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </section>
    </div>
  );
}

function AccessPanel({ matrix }: { matrix: AccessMatrix }) {
  const cellMap = useMemo(() => {
    const map = new Map<string, string>();
    matrix.cells.forEach((cell) => map.set(`${cell.principal}:${cell.asset_id}`, cell.permission));
    return map;
  }, [matrix.cells]);
  const riskyReason = new Map(matrix.risky_combinations.map((item) => [item.principal, item.reason]));
  const risky = new Set(matrix.risky_combinations.map((item) => item.principal));

  return (
    <div className="page-grid">
      <header className="page-header">
        <div>
          <p className="eyebrow">Role exposure</p>
          <h1>Access Matrix</h1>
        </div>
      </header>
      <section className="table-panel">
        <table className="access-table">
          <thead>
            <tr>
              <th>Principal</th>
              {matrix.assets.map((asset) => (
                <th key={asset.id}>
                  <span className="th-label">
                    {asset.name}
                    <InfoTooltip text={`PHI asset with current rolled-up risk score ${asset.risk_score}. Access here may increase minimum-necessary and auditability risk.`} />
                  </span>
                </th>
              ))}
            </tr>
          </thead>
          <tbody>
            {matrix.principals.map((principal) => (
              <tr key={principal} className={risky.has(principal) ? "risk-row" : ""}>
                <td>
                  <strong>{principal}</strong>
                  {risky.has(principal) && (
                    <HoverExplain text={riskyReason.get(principal) ?? "This principal has a risky access combination."}>
                      <span>combined PHI</span>
                    </HoverExplain>
                  )}
                </td>
                {matrix.assets.map((asset) => {
                  const permission = cellMap.get(`${principal}:${asset.id}`);
                  return (
                    <td key={asset.id} className={permission ? "has-access" : ""}>
                      {permission ? (
                        <HoverExplain text={`${principal} has ${permission} access to ${asset.name}. Asset risk score: ${asset.risk_score}.`}>
                          {permission}
                        </HoverExplain>
                      ) : (
                        <HoverExplain text={`${principal} has no modeled grant to ${asset.name}.`}>
                          -
                        </HoverExplain>
                      )}
                    </td>
                  );
                })}
              </tr>
            ))}
          </tbody>
        </table>
      </section>
    </div>
  );
}

function ReportPanel({ report }: { report: ReportPayload }) {
  return (
    <div className="page-grid">
      <header className="page-header">
        <div>
          <p className="eyebrow">Evidence package</p>
          <h1>{report.title}</h1>
        </div>
        <div className="scan-meta">
          <span>Generated</span>
          <strong>{formatDate(report.generated_at)}</strong>
        </div>
      </header>
      <section className="report-grid">
        <div className="panel report-summary">
          <h2>Executive Summary</h2>
          <p>{report.executive_summary.message}</p>
          <div className="summary-strip">
            <strong>{report.executive_summary.risk_score}</strong>
            <span>{report.executive_summary.critical_findings} critical</span>
            <span>{report.executive_summary.high_findings} high</span>
            <span>{report.executive_summary.phi_assets} PHI assets</span>
          </div>
        </div>
        <div className="panel">
          <h2>Limitations</h2>
          <ul className="plain-list">
            {report.limitations.map((item) => (
              <li key={item}>{item}</li>
            ))}
          </ul>
        </div>
      </section>
      <section className="panel">
        <div className="panel-header">
          <h2>Technical Findings</h2>
          <span className="pill">{report.technical_findings.length} included</span>
        </div>
        <div className="report-findings">
          {report.technical_findings.slice(0, 8).map((finding) => (
            <article key={finding.id}>
              <SeverityBadge severity={finding.severity} />
              <h3>{finding.title}</h3>
              <p>{finding.remediation_summary}</p>
            </article>
          ))}
        </div>
      </section>
    </div>
  );
}

function SeverityBadge({ severity }: { severity: Severity }) {
  return (
    <span className={`severity ${severity}`} tabIndex={0} aria-label={severityHelp[severity]}>
      {severity}
      <span className="tooltip-panel" role="tooltip">{severityHelp[severity]}</span>
    </span>
  );
}

function layoutNodes(nodes: GraphNodeDto[], findingById: Map<string, FindingSummary>): Node[] {
  const lanes: Record<string, { x: number; y: number; count: number }> = {
    database: { x: 0, y: 90, count: 0 },
    schema: { x: 210, y: 90, count: 0 },
    table: { x: 420, y: 0, count: 0 },
    view: { x: 420, y: 0, count: 0 },
    export: { x: 420, y: 0, count: 0 },
    column: { x: 670, y: 0, count: 0 },
    role: { x: 120, y: 360, count: 0 },
    external_destination: { x: 940, y: 110, count: 0 },
    ai_tool: { x: 940, y: 250, count: 0 },
    finding: { x: 1190, y: 0, count: 0 },
    control: { x: 1480, y: 70, count: 0 }
  };
  return nodes.map((item) => {
    const lane = lanes[item.type] ?? lanes.table;
    const yStep = item.type === "finding" ? 98 : item.type === "column" ? 88 : item.type === "table" ? 118 : 92;
    const position = { x: lane.x, y: lane.y + lane.count * yStep };
    lane.count += 1;
    const finding = findingById.get(item.id);
    const nodeHelp = graphNodeHelp(item, finding);
    const tags = item.classifications.slice(0, 3);
    return {
      id: item.id,
      position,
      data: {
        label: (
          <div className="flow-card">
            <div className="flow-kicker">
              <span className="flow-type">{item.type.replace("_", " ")}</span>
              <InfoTooltip text={nodeHelp} />
            </div>
            <strong>{finding ? finding.title : item.label}</strong>
            {tags.length > 0 && (
              <em>{tags.join(", ")}{item.classifications.length > tags.length ? ` +${item.classifications.length - tags.length}` : ""}</em>
            )}
            {item.rowCount ? <small>{item.rowCount.toLocaleString()} rows</small> : null}
          </div>
        )
      },
      className: `risk-node ${riskClass(finding?.risk_score ?? item.riskScore)} ${item.type}`,
      style: {
        width: item.type === "finding" ? 240 : item.type === "column" ? 230 : 190
      }
    };
  });
}

function graphNodeHelp(item: GraphNodeDto, finding?: FindingSummary) {
  if (finding) {
    return `${finding.severity.toUpperCase()} finding scored ${finding.risk_score}: ${finding.description}`;
  }
  if (item.type === "column") {
    const labels = item.classifications.length ? item.classifications.join(", ") : "no PHI-risk labels";
    return `${item.label} is a column with ${labels}. Risk score ${item.riskScore}.`;
  }
  if (item.type === "table" || item.type === "view" || item.type === "export") {
    return `${item.label} is a ${item.type} with rolled-up risk score ${item.riskScore}. Row estimate: ${item.rowCount?.toLocaleString() ?? "unknown"}.`;
  }
  if (item.type === "role") {
    return `${item.label} is a modeled principal. Edges show which PHI assets it can read or administer.`;
  }
  if (item.type === "control") {
    return `${item.label} is a HIPAA-oriented control mapping used to explain why findings matter.`;
  }
  return item.description || `${item.label} is a ${item.type.replace("_", " ")} node in the Intelligence graph.`;
}

function layoutEdges(edges: GraphEdgeDto[]): Edge[] {
  return edges.map((edge) => ({
    id: edge.id,
    source: edge.source,
    target: edge.target,
    label: edge.type === "CONTAINS" ? undefined : edge.label,
    animated: edge.type === "EXPORTED_TO" || edge.type === "SENT_TO" || edge.type === "DERIVES_FROM",
    markerEnd: { type: MarkerType.ArrowClosed, width: 18, height: 18 },
    className: `edge-${edge.type.toLowerCase().replaceAll("_", "-")}`,
    style: { strokeWidth: edge.type === "READ_BY" ? 1.2 : 1.8 }
  }));
}

function riskClass(score: number) {
  if (score >= 85) return "critical";
  if (score >= 70) return "high";
  if (score >= 40) return "moderate";
  return "low";
}

function statusClass(status: string) {
  if (status === "Not ready") return "critical";
  if (status === "Review") return "moderate";
  return "low";
}

function labelize(value: string) {
  return value.replaceAll("_", " ").replace(/\b\w/g, (char) => char.toUpperCase());
}

function formatDate(value: string) {
  return new Intl.DateTimeFormat("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
    hour: "numeric",
    minute: "2-digit"
  }).format(new Date(value));
}
